name: Deployment Workflow

on:
  push:
    branches:
      - main
      - staging

jobs:
  setup-and-build:
    name: Setup and Build
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install Python dependencies
      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      # Setup Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'

      # Build Go project
      - name: Build Go Project
        run: go build raja.go

      # Run Python script
      - name: Run Python Script
        run: python3 d.py

  deploy-development:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: setup-and-build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Development
        run: echo "Deploying to Development Environment"

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: setup-and-build
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging Environment"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: setup-and-build
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'

    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production Environment"
        
